package com.greatingcard.nammarailubuddy.models

data class LiveTrainDetails(
    val trainNumber: String,
    val trainName: String,
    val source: String,
    val destination: String,
    val sourceStationCode: String = "",
    val destinationStationCode: String = "",
    val currentStation: String,
    val currentStationCode: String = "",
    val nextStation: String,
    val nextStationCode: String = "",
    val platform: String,
    val delayMinutes: Int,
    val runStatus: TrainRunStatus,
    val eta: String,
    val departureTime: String,
    val arrivalTime: String,
    val lastUpdated: String,
    val latitude: Double?,
    val longitude: Double?,
    val mapLatitude: Double? = null,
    val mapLongitude: Double? = null,
    val mapLocationLabel: String = "",
    val gpsUnavailable: Boolean = false,
    val routeSummary: String,
    val coachSequence: String,
    val scheduleStationCodes: List<String> = emptyList(),
    val activeStatusText: String = "",
    val aheadDistanceText: String = "",
    val statusAsOf: String = "",
    val rawJson: String = ""
)
